server:
  port: 8080

management:
  server:
    port: 9009
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      #      show-details: always
      show-components: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/manage"

info:
  app:
    name: onestop-actuator
    company: ai


logging:
  level:
    ai.onestop: TRACE