server:
  port: 8080

  tomcat:
    mbeanregistry:
      enabled: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      connection-timeout: 3000
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

management:
  server:
    port: 8080
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      #      show-details: always
      show-components: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

info:
  app:
    name: onestop-actuator
    company: ai


logging:
  level:
    ai.onestop: TRACE